=== LuisSantiagoMartin/71456_file-admin-2p/src/studentSchema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "Student",
  "type": "object",
  "properties": {
    "idStudent": { "type": "integer" },
    "name": { "type": "string" },
    "lastName": { "type": "string" },
    "degree": { "type": "integer" },
    "semester": { "type": "string" },
    "promedio": { "type": "number" },
    "email": { "type": "string", "format": "email" },
    "age": { "type": "integer", "minimum": 0 },
    "status": { 
      "type": "string",
      "enum": ["ACTIVE", "INACTIVE", "SUSPENDED"]
    }
  },
  "required": [
    "idStudent", "name", "lastName", "degree",
    "semester", "promedio", "email", "age", "status"
  ]
}

=== LuisSantiagoMartin/71456_file-admin-2p/studentsDB.json
[
  {"idStudent":1,"name":"Luis","lastName":"Martin","degree":1,"semester":"7","promedio":8.0,"email":"luis@mail.com","age":21,"status":"ACTIVE"},
  {"idStudent":2,"name":"David","lastName":"Gonzalez","degree":2,"semester":"7","promedio":9.0,"email":"david@mail.com","age":21,"status":"ACTIVE"},
  {"idStudent":3,"name":"Antonio","lastName":"Velazquez","degree":6,"semester":"7","promedio":9.0,"email":"anto@mail.com","age":22,"status":"INACTIVE"}
]
